import type { Metadata } from "next";
import "./globals.css";
import { Atkinson_Hyperlegible } from "next/font/google";
import Navbar from "./components/Navbar";
import { StateContext } from "./context/statecontext";
import { Toaster } from "react-hot-toast";
import Footer from "./components/Footer";
const atkinson = Atkinson_Hyperlegible({
  subsets: ["latin"],
  weight: ["400", "700"], // regular + bold
  display: "swap",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={atkinson.className}>
        <StateContext>
          <Navbar />
          {children}
          <Toaster position="bottom-center" />
          <Footer />
        </StateContext>
      </body>
    </html>
  );
}
