import Link from "next/link";
import { AiOutlineArrowLeft, AiOutlineArrowRight } from "react-icons/ai";

export default function TOS() {
  return (
    <>
      <div className="flex justify-between items-center mb-8">
        <Link href="/admin/dashboard" className="flex items-center gap-2">
          <AiOutlineArrowLeft />
          Back to Dashboard
        </Link>
      </div>
      <div className="max-w-3xl mx-auto px-6 py-12">
        <h1 className="text-4xl font-bold text-center mb-2">Watch Shop</h1>
      <h1>Watch Shop</h1>
<h2>Terms of Service</h2>
<p><em>Effective Date: March 8, 2026</em></p>
<p><em>Portfolio Demonstration Project</em></p>

<hr />

<section>
  <h2>1. About This Project</h2>
  <p>
    Watch Shop is a portfolio demonstration project built to learn how to implement
    automated accessibility auditing in a CI/CD pipeline. The ecommerce context was
    chosen deliberately — it provides a realistic, feature-rich environment to test
    against WCAG standards. It is not a commercial operation. No products are
    physically sold or shipped.
  </p>
  <p>
    By using this application you acknowledge that it is a learning project and not
    a real store.
  </p>
</section>

<hr />

<section>
  <h2>2. Payments</h2>
  <p>
    This application operates in Stripe test mode. Real payment cards will not be
    accepted and no real charges will occur. Stripe's test environment physically
    rejects real card numbers.
  </p>
  <p>To complete a test transaction use Stripe's test card:</p>
  <ul>
    <li>Card number: 4242 4242 4242 4242</li>
    <li>Expiry: any future date</li>
    <li>CVC: any three digits</li>
    <li>ZIP: any five digits</li>
  </ul>
  <p>
    No money will be charged. No real financial transaction takes place.
  </p>
</section>

<hr />

<section>
  <h2>3. Orders and Shipping</h2>
  <p>
    Orders placed through this application are demo transactions only. No physical
    products exist and no shipments will be sent to your address.
  </p>
  <p>
    Tracking numbers generated by this application come from the FedEx sandbox
    (test) environment. They are real-looking tracking numbers but represent no
    physical package. You may see the tracking number appear on the FedEx website
    but it will never update its status.
  </p>
</section>

<hr />

<section>
  <h2>4. Your Data</h2>
  <p>
    All personal information you submit — including your name, email address, and
    shipping address — is scheduled for permanent deletion within 24 hours of your
    order being placed. Full details of how your data is collected, protected, and
    deleted are described in our Privacy Policy.
  </p>
  <p>
    By placing a demo order you consent to your information being processed for the
    sole purpose of demonstrating the ecommerce functionality of this application,
    and to its deletion within 24 hours.
  </p>
</section>

<hr />

<section>
  <h2>5. Acceptable Use</h2>
  <p>You agree not to:</p>
  <ul>
    <li>Use this application for any commercial purpose.</li>
    <li>Attempt to access the admin dashboard without authorisation.</li>
    <li>Attempt to exploit, reverse engineer, or disrupt the application.</li>
    <li>Submit false or malicious data intended to harm the application or its infrastructure.</li>
    <li>Use automated tools to scrape, flood, or stress test the application without prior permission.</li>
  </ul>
</section>

<hr />

<section>
  <h2>6. Intellectual Property</h2>
  <p>
    This project is released under the MIT License. You are free to copy, modify,
    and learn from the code. However it is not intended for commercial use without
    prior permission from the project owner.
  </p>
  <p>
    The design, written content, and documentation in this project are the work of
    the project owner and may not be reproduced for commercial purposes.
  </p>
</section>

<hr />

<section>
  <h2>7. Availability</h2>
  <p>
    This is a portfolio project hosted on Vercel's free tier. We make no guarantees
    about uptime, availability, or continuity of service. The application may be
    taken offline, modified, or discontinued at any time without notice.
  </p>
</section>

<hr />

<section>
  <h2>8. Limitation of Liability</h2>
  <p>
    This application is provided as-is for demonstration purposes only. The project
    owner accepts no liability for any damages, losses, or issues arising from your
    use of this application. Because no real transactions occur and all personal data
    is deleted within 24 hours, the potential for harm is by design extremely limited.
  </p>
</section>

<hr />

<section>
  <h2>9. Third-Party Services</h2>
  <p>
    This application integrates with third-party services including Stripe, MongoDB
    Atlas, Brevo, FedEx, and Vercel. Your use of this application means your data
    may pass through these services as described in our Privacy Policy. Each
    third-party service operates under its own terms of service.
  </p>
</section>

<hr />

<section>
  <h2>10. Changes to These Terms</h2>
  <p>
    These terms may be updated as the project evolves. The effective date at the top
    of this page will always reflect the most recent version. Continued use of the
    application after changes are made constitutes acceptance of the updated terms.
  </p>
</section>

<hr />

<section>
  <h2>11. Contact</h2>
  <p>
    If you have questions about these terms please contact the project owner through
    the contact information provided in the project repository.
  </p>
</section>

<hr />

<footer>
  <p><em>Watch Shop — Portfolio Demonstration Project — Not a commercial service</em></p>
  <p><em>Built with Next.js · MongoDB · Stripe · WebAuthn · FedEx · Brevo · Vercel</em></p>
</footer>
     </div>
    </>
  );
}